name: Prisma Cloud Compute Image Scan

on: [push, pull_request]

env:
  PCC_USER: a8ab63a5-d570-4ad9-8e46-bf60d2ee6a18
  PCC_PASS: dCzy2IIqqDF/0N+VXufKAkA0rg8=
  PCC_CONSOLE_URL: https://europe-west3.cloud.twistlock.com/eu-2-143567095
  IMAGE_NAME: anjalispatil/microservicedemo

jobs:
  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        # Defaults are sufficient generally
        # https://github.com/actions/checkout#usage

      - name: Build the image
        run: docker build -t $IMAGE_NAME .

      - name: Download twistcli from the Prisma Cloud Compute Console
        run: |
          curl --user $PCC_USER:$PCC_PASS --output ./twistcli $PCC_CONSOLE_URL/api/v1/util/twistcli
          chmod a+x ./twistcli

      - name: Scan the image
        run: ./twistcli images scan --address $PCC_CONSOLE_URL --user $PCC_USER --password $PCC_PASS --details $IMAGE_NAME
